### ISSUE TITLE
Causing below issue during installation.

### ISSUE THREAD

**Issue by rakeshaspl** [php-translation/translator#8]
**rakesh@aum224:~/web/demoproj$ php composer.phar require php-translation/translator**
Using version ^0.1.2 for php-translation/translator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-translation/translator ^0.1.2 -> satisfiable by php-translation/translator[0.1.2].
    - php-translation/translator 0.1.2 requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Installation failed, reverting ./composer.json to its original content.**

**Comment by bocharsky-bw** [comment]
Hey, you need to install a `php-http` client first, for example `php-http/guzzle6-adapter`.

See the full list of packages that provide `php-http/client-implementation`:
https://packagist.org/providers/php-http/client-implementation

So, the solution is:
1. `composer require php-http/guzzle6-adapter`
2. `composer require php-translation/translator`

**Comment by rakeshaspl** [comment]
Thanks working now.
